### ISSUE TITLE
Unit Testing Support for the Simulation?

### ISSUE THREAD

**Issue by JamieSinn** [Open-RIO/ToastAPI#13]
We'd like to set up a full CI system for our code, and I'm not entirely sure whether the simulation supports unit testing, if not oh well, and I'll write one. If it does, any docs :D

**Comment by JaciBrunning** [comment]
Simulation does support a form of CI integration. Toast is being tested with Travis CI and can be done using the `./gradlew verify` command in your .travis.yml file. Currently, some changes are being done for 2016.

Things like I2C and SPI are currently not supported in simulation, simply due to the fact that their behaviour is reliant on the implementation.
