### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by c0d3rman** [Open-RIO/ToastAPI#6]
Hi,

My team (4904) has been trying to use Toast for a little while, but couldn't figure it out.
I'm the programming captain and I finally decided to try it myself.
The instructions to actually set up and use Toast are a bit hard to find and unclear.
I almost gave up on the readme before I found the "Quickstart" section almost at the bottom.
When I got to the quickstart repo, I was confused as to it not actually giving me any instructions. Poking around in it revealed the actual instructions in the "Toast" folder.
From there I had trouble running the gradlew file, as I am on mac and it had Windows linebreaks (a fact revealed by the error message, which said something about "bash/r".) It also needed chmod +x, a step worth mentioning in the instructions.
Now I am trying to get simulation working (as I don't have access to a RoboRIO over the summer) and don't entirely understand what to do. Should I copy the "Toast" project and put my existing code inside "src/main/java"? Do I make a fresh copy for every new project? Do I include something in my projects and extend ToastModule instead of RobotBase? Where does "-sim your.main.Class" go in Eclipse's Run Configurations?
I think going through the entire setup workflow or, better yet, making a video would make it a lot easier to get started. Also, making it clear what Toast is and how it interacts with your code. Toast looks great, but right now it is impossible for anyone without a lot of experience to use it.
All that said, Toast looks awesome and I can't wait to have my team use it. We really appreciate what you're doing for the FRC community!

**Comment by JaciBrunning** [comment]
Hey there. Thanks for the input, I'll try my best to respond.   

The setup procedure of Toast is currently undergoing quite a lot of changes, as we're starting to move over to V2 of Toast within the coming weeks. 

For the bash line endings and permissions, that's something that I'm trying to find a solution to. Toast deployment and zipping is done on a windows machine, however I'm trying to remedy that as soon as possible. 

The gradle stuff is pretty simple, for the most part `gradlew idea` or `gradlew eclipse` is all you need, although deployment instructions for the RoboRIO are elsewhere. When these commands are run, Toast will generate the Run Configurations for you, for both Simulation and Verification. Your source files should be contained in `src/main/java`. ToastModule (or any derivitaves) should be extended instead of RobotBase, and from there on you're free to do whatever you want.  

Once we hit the V2 stage, documentations will be overhauled to support the new workflow. These instructions will, however, work for the latest versions of Toast available for download. I'll be sure to ping this issue when some updates occur to fix the Bash Line Endings and Permissions. Thanks for keeping an eye on Toast.  
~Jaci

**Comment by JaciBrunning** [comment]
Line Endings and Unix Permissions should now be fixed in the [Toast Universal Release](https://github.com/Open-RIO/ToastAPI/releases/tag/Universal)

**Comment by JaciBrunning** [comment]
Some Wiki entries have been added for Start-To-Finish Module Development, Toast Deployment, Java/JS Module Development and other topics to the [Toast Wiki](https://github.com/Open-RIO/ToastAPI/wiki). If anything's still unclear feel free to reopen the issue and I'll fix it all up as soon as I can :+1:
